# Generated by Django 5.1 on 2024-09-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='received_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
